### ISSUE TITLE
Check that required dependencies are installed at the start of runtime before using them

### ISSUE THREAD

**Issue by drjaska** [nevesnunes/sh-manpage-completions#2]
Shouldn't there be a runtime dependency check that `flex` is an executable before its call on Makefile's line `flex $^` in

```make
LEXERS = $(wildcard *.l)
...
lex.yy.cc: $(LEXERS)
	flex $^
```

and a README.md header + list of dependencies so the users know to install them before runtime errors? For me it's worrisome that there are no dependency notes, checks nor exit on error behavior. :S

Also run.sh has dependencies other than flex, namely: make, python3, (coreutils), (optionally fzf for bash), sed, and awk for now, even though most systems should have them I'd still name them.

**Comment by nevesnunes** [comment]
Sure, I've added a simple check for these at the beginning of the script. I didn't add installation since it depends on distro choice, but feel free to improve it.
